name: posetail
channels: 
  - defaults
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.12
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - tensorflow-gpu<=2.12.0
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - tqdm=4.67.1
  - mamba
  - jupyter
  - notebook
  - pip
  - pip:
    - aniposelib
    - easydict==1.13
    - einops==0.7.0
    - frozendict==2.4.6
    - opencv-python==4.9.0.80
    - pytorch-memlab==0.3.0
    - toml==0.10.2
    - wandb==0.19.5
    - wget==3.2