[wandb]
project_name = '3d-tracker-test'
path = '/data/results/lili/posetail'
mode = 'online' # 'online', 'offline', 'disabled'

[dataset]
batch_size = 1

[dataset.train]
# prefix = '/nvme1/data/animal-datasets-processed/kubric-multiview'
prefix = '/data/animal-datasets-processed/posetail-tests/single-subject-filtered-3500'
# prefix = '/data/animal-datasets-processed/posetail-tests/single-subject-35000'
n_frames = 16
max_res = 256

[dataset.test]
dataset_name = 'rat7m'
prefix = '/nvme1/data/animal-datasets/rat7m'
sub_pattern = 's([5])-d([2])'
n_frames = 16
project_2d = false


[devices]
device = 'cuda:0'


[model]
track_3d = true
mode_3d = "minicubes"

# processing
stride_length = 8
stride_overlap = 4
downsample_factor = 2

# cube (only used for 3d)
cube_dim = 64
cube_extent = 500 # rat7m
# cube_extent = 50 # kubric

# correlation
corr_levels = 4
corr_radius = 2
# corr_hidden_dim = 384
# corr_output_dim = 256
# corr_output_dim = 125
# corr_hidden_dim = 1024
# corr_output_dim = 512
corr_hidden_dim = 1586
corr_output_dim = 1024

# triplane
upsample_factor = 1

# transformer
max_freq = 10
n_iters = 4
embedding_dim = 384
# embedding_dim = 512
latent_dim = 64
# encoding_dim = 64 # this doesn't change anything
n_virtual = 64
n_heads = 8
n_time_space_blocks = 6
embedding_factor = 4


[training]
seed = 3
n_epochs = 600
scheduler_type = 'multisteplr'
# scheduler_type = 'onecyclelr'
use_half_precision = true
max_grad_norm = 1.0
checkpoint_freq = 20
eval_freq = 1
print_freq = 1
debug_ix = -1

[training.optimizer]
learning_rate = 3e-5
weight_decay = 1e-6
# weight_decay = 0
amsgrad = true

[training.scheduler]
# milestones = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550]
# gamma = 0.6
milestones = [200]
gamma = 0.1
# steps_per_epoch = 218
# pct_start = 0.05
# cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 6
# delta = 0.1
delta = 3
use_huber = false

# weights for computing total loss
vis_loss_weight = 2
conf_loss_weight = 1
coords_loss_weight = 0.05
