[wandb]
project_name = 'posetail-pretrain'
# path = '/data/results/katie'
# path = '/groups/karashchuk/home/ruppk2/results'
path = '/groups/karashchuk/home/karashchukl/results/posetail-pretrain'
mode = 'online' # 'online', 'offline', 'disabled'


[dataset]
batch_size = 1
# prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-tests/kubric-multiview-subset'
# prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-pretraining'
prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-pretraining-visibility'

[dataset.train]
split = 'train'
n_frames = 16
max_res = 288
cams_to_sample = [1, 10] 
kpts_to_sample = [256, 512] 
aug_prob = 0.25
enable_kpt_filtering = false
cam_thresh_for_vis = 1

[dataset.val]
split = 'val'
n_frames = 16
max_res = 288
cams_to_sample = 5
kpts_to_sample = 60
aug_prob = 0.0

[dataset.test]
split = 'test'
n_frames = 16
max_res = 288
project_2d = false


[devices]
device = 'cuda'


[model]
track_3d = true
mode_3d = 'triplane' # 'minicubes'

# temporal processing
stride_length = 8
stride_overlap = 4

# resnet
downsample_factor = 4
hiera_requires_grad = false

# cube (only used for 3d)
cube_dim = 64
cube_extent = 15 # kubric
# cube_extent = 500

# correlation
corr_levels = 4 
corr_radius = 3

corr_hidden_dim = 384 
corr_output_dim = 256
# corr_hidden_dim = 1024
# corr_output_dim = 256 
# corr_hidden_dim = 1586
# corr_output_dim = 1024
# corr_hidden_dim = 1024
# corr_output_dim = 512

# triplane 
upsample_factor = 1

# transformer
max_freq = 10
n_iters = 4
embedding_dim = 384
latent_dim = 64 
n_virtual = 64 
n_heads = 8 
n_time_space_blocks = 6
embedding_factor = 4 


[training]
seed = 3
n_iterations = 600000
# scheduler_type = 'multisteplr' # 'onecyclelr'
scheduler_type = 'onecyclelr'
max_grad_norm = 1.0
checkpoint_freq = 20480 # in iterations
eval_metric_freq = 16 # in iterations
val_freq = 16 # in iterations
print_freq = 1 # in iterations
debug_ix = -1 # only works for val 

[training.optimizer]
learning_rate = 1e-4
weight_decay = 1e-5
amsgrad = false

[training.scheduler]
# milestones = []
# milestones = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550]
# gamma = 0.1

pct_start = 0.05
cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 9
delta = 6
use_vis_loss = true
use_conf_loss = true
use_huber_loss = false
use_feature_loss = false

# weights for computing total loss 
vis_loss_weight = 1
conf_loss_weight = 1
coords_loss_weight = 0.05
feature_loss_weight = 1.0

