[wandb]
project_name = 'posetail-odyssey-finetuning'
# path = '/data/results/lili/posetail'
path = '/groups/karashchuk/home/karashchukl/results/posetail-odyssey-finetuning'
mode = 'online' # 'online', 'offline', 'disabled'

[dataset]
batch_size = 1
num_workers = 12
# prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-tests/kubric-multiview-subset'
# prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-tests/wrapped'
# prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-pretraining-visibility'
prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-finetuning-v2'
# prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-finetuning-test'
datasets_to_exclude = ['anipose-fly', 'allen-mouse', 'pair-r24m']

[dataset.train]
split_dir = 'train'
n_frames = 16
min_res = 256
max_res = 256
cams_to_sample = [1, 8] 
kpts_to_sample = [128, 128]
aug_prob = 0.25
enable_kpt_filtering = true
cam_thresh_for_vis = 1
balance_datasets = true
n_samples_per_dataset = -1
crop_to_points = true
speed_thresh = 1.0
query_anytime = true
query_edge_bias = 25.0
prop_dynamic_kpts_to_sample = 0.95
prob_2d_only = 0.25
no_nan_coords = false

[dataset.val]
split_dir = 'val'
n_frames = 16
max_res = 256
cams_to_sample = 5
kpts_to_sample = 64
aug_prob = 0.0
crop_to_points = true
speed_thresh = 1.0
prop_dynamic_kpts_to_sample = 0.7
query_anytime = false

[dataset.test]
split_dir = 'test'
max_res = 256
n_frames = 16
project_2d = false
aug_prob = 0.0

[devices]
device = 'cuda'


[model]
mode_3d = "encoder"

video_encoder_version = 'large'
video_encoder_requires_grad = true
video_encoder_hierarchical = true

# processing
stride_length = 16
image_size = 256
query_patch_size = 9
per_camera_cube_scale = true

# query encoder
max_freq = 10
embedding_dim = 256
use_volume_embedding = false
corr_radius = 2
principal_point_embedding = false

# decoder
latent_dim = 512
n_heads = 8
n_time_space_blocks = 8
embedding_factor = 4
use_camera_self_attention = true
output_mode = "direct" # direct, residual, grid
scene_encoder_proj = false
head_3d_grid_size = 16
head_3d_grid_radius = 1.0

[training]
seed = 3
# residual
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-vjepa-new/wandb/run-20260504_111253-npcd6yc9/files/checkpoints/checkpoint_00399999.pth'
# direct
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-vjepa-new/wandb/run-20260504_230632-eslwt90p/files/checkpoints/checkpoint_00399999.pth'

# direct - aug
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-vjepa-new/wandb/run-20260506_115705-fxhxtjei/files/checkpoints/checkpoint_00399992.pth'
# residual - aug
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-vjepa-new/wandb/run-20260506_115918-e1syp7fo/files/checkpoints/checkpoint_00399992.pth'

# residual finetuned
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-vjepa-finetuning/wandb/run-20260506_193609-swq2iqr1/files/checkpoints/checkpoint_00501760.pth'

# residual 3d - new pretrain
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-odyssey-pretrain/wandb/run-20260512_160837-zbc781ha/files/checkpoints/checkpoint_00399996.pth'

# residual 3d - per camera cube scale
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-odyssey-pretrain/wandb/run-20260518_111742-y2ird8f0/files/checkpoints/checkpoint_00399996.pth'

# direct 3d - no 2d
# checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-odyssey-pretrain/wandb/run-20260519_232230-5wo436xb/files/checkpoints/checkpoint_00399996.pth'

# direct 3d - with 2d
checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-odyssey-pretrain/wandb/run-20260520_165302-iuvydycq/files/checkpoints/checkpoint_00399996.pth'


finetune = true
n_iterations = 800000
# scheduler_type = 'multisteplr'
scheduler_type = 'schedulefree'
max_grad_norm = 5.0
checkpoint_freq = 10240 # in iterations
eval_metric_freq = 16 # in iterations
val_freq = 64 # in iterations
print_freq = 64 # in iterations
debug_ix = -1 # only works for val 

[training.optimizer]
learning_rate = 5e-5
weight_decay = 0.005
warmup_steps = 3000
beta1 = 0.9
beta2 = 0.999

[training.scheduler]
# milestones = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550]
# milestones = []
# gamma = 0.8
# milestones = [200]
# gamma = 0.1
# steps_per_epoch = 218

# pct_start = 0.025
# cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 3
# delta = 0.1
delta = 6
use_huber_loss = false

# weights for calculating total loss (use 0 to not compute a specific loss)
vis_loss_weight = 4
conf_loss_weight = 0.0
conf_2d_loss_weight = 0.0
occluded_coords_loss_weight = 0.05
feature_loss_weight = 0.0

coords_loss_weight = 1.0
coords_loss_direct_weight = 1.0
coords_loss_rays_weight = 0.1
coords_loss_triangulate_weight = 0.0
coords_loss_2d_weight = 1.0
coords_loss_depth_weight = 0.1
