[wandb]

project_name = 'posetail-test' # 'posetail-finetuning'
path = '/groups/karashchuk/home/ruppk2/results/posetail-finetuning'
mode = 'disabled' # 'online', 'offline', 'disabled'

[dataset]
batch_size = 1
num_workers = 1 # 96
prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-finetuning'

[dataset.train]
split_dir = 'train'
n_frames = 16
min_res = 256
max_res = 352
cams_to_sample = [1, 10] 
kpts_to_sample = [32, 256]
aug_prob = 0.25
enable_kpt_filtering = true
cam_thresh_for_vis = 1
balance_datasets = true
n_samples_per_dataset = -1

[dataset.val]
split_dir = 'val'
n_frames = 16
max_res = 288
cams_to_sample = 5
kpts_to_sample = 60
aug_prob = 0.0

[dataset.test]
split_dir = 'test'
max_res = 288
n_frames = 16
project_2d = false


[devices]
device = 'cuda'


[model]
mode_3d = "minicubes"
hiera_requires_grad = false

# processing
stride_length = 8
stride_overlap = 4
downsample_factor = 4

# cube (only used for triplane)
cube_dim = 64
# cube extent only used for triplane
# cube_extent = 500 # rat7m
cube_extent = 5 # kubric

# correlation
corr_levels = 5 # includes extra cube
corr_radius = 2
corr_hidden_dim = 256
corr_output_dim = 128

# triplane
upsample_factor = 1

# transformer
max_freq = 10
n_iters = 4
embedding_dim = 384
latent_dim = 64
n_virtual = 64
n_heads = 8
n_time_space_blocks = 6
embedding_factor = 4
vc_head_requires_grad = false

[training]
seed = 3
checkpoint_path = '/groups/karashchuk/home/karashchukl/results/posetail-pretrain/wandb/run-20260211_151402-9iwgznvx/files/checkpoints/checkpoint_599992.pth'
n_iterations = 50 # 600000
scheduler_type = 'onecyclelr' # 'onecyclelr' or 'multisteplr'
max_grad_norm = 1.0
checkpoint_freq = 20480 # in iterations
eval_metric_freq = 16 # in iterations
val_freq = 64 # in iterations
print_freq = 1 # in iterations
debug_ix = -1 # only works for val 

[training.optimizer]
learning_rate = 1e-5
weight_decay = 1e-5
amsgrad = false

[training.scheduler]
# milestones = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550]
# gamma = 0.8
# steps_per_epoch = 218
pct_start = 0.05
cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 9
delta = 6
use_huber_loss = false

# weights for calculating total loss (use 0 to not compute a specific loss)
vis_loss_weight = 1
conf_loss_weight = 1
coords_loss_weight = 0.05
occluded_coords_loss_weight = 0.01
feature_loss_weight = 1.0
