[wandb]
project_name = '3d-tracker-test'
path = '/data/results/lili/posetail'
mode = 'online' # 'online', 'offline', 'disabled'

[dataset]
batch_size = 4

[dataset.train]
prefix = '/nvme1/data/animal-datasets-processed/posetail-tests/test-3500'
n_frames = 16
max_res = 256

[dataset.test]
dataset_name = 'rat7m'
prefix = '/nvme1/data/animal-datasets/rat7m'
sub_pattern = 's([5])-d([2])'
n_frames = 16
project_2d = false


[devices]
device = 'cuda:0'


[model]
track_3d = true
mode_3d = "minicubes"

# processing
stride_length = 8
stride_overlap = 4
downsample_factor = 2

# cube (only used for 3d)
cube_dim = 64
cube_extent = 500

# correlation
corr_levels = 4
corr_radius = 3
# corr_hidden_dim = 384
# corr_output_dim = 256
# corr_output_dim = 125
corr_hidden_dim = 1024
corr_output_dim = 512

# triplane
upsample_factor = 1

# transformer
max_freq = 10
n_iters = 4
embedding_dim = 384
latent_dim = 64
encoding_dim = 64
n_virtual = 64
n_heads = 8
n_time_space_blocks = 3
embedding_factor = 4


[training]
seed = 3
n_epochs = 500
scheduler_type = 'multisteplr'
# scheduler_type = 'onecyclelr'
use_half_precision = true
max_grad_norm = 1
checkpoint_freq = 25
eval_freq = 1
print_freq = 1
debug_ix = -1

[training.optimizer]
learning_rate = 0.0001
weight_decay = 0.00001
# weight_decay = 0
amsgrad = true

[training.scheduler]
milestones = [250]
gamma = 0.1
# steps_per_epoch = 218
# pct_start = 0.05
# cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 6
delta = 20
use_huber = true

# weights for computing total loss
vis_loss_weight = 2
conf_loss_weight = 1
coords_loss_weight = 0.1
