[wandb]
project_name = 'posetail-tests'
# path = '/data/results/katie'
path = '/groups/karashchuk/home/karashchukl/results/posetail'
mode = 'online' # 'online', 'offline', 'disabled'


[dataset]
batch_size = 1

[dataset.train]
# prefix = '/data/animal-datasets-processed/posetail-tests/single-subject-filtered-3500'
# prefix = '/nvme1/data/animal-datasets-processed/kubric-multiview'
prefix = '/groups/karashchuk/karashchuklab/animal-datasets-processed/kubric-multiview'
n_frames = 16
max_res = 256
cams_to_sample = 5 # default: -1 
kpts_to_sample = 60 # default: -1

[dataset.val]
# prefix = '/data/animal-datasets-processed/posetail-tests/s4-d1-filtered-350'
n_frames = 16
max_res = 256
cams_to_sample = -1 # default: -1 
kpts_to_sample = -1 # default: -1

[dataset.test]
# dataset_name = 'rat7m'
# prefix = '/nvme1/data/animal-datasets/rat7m'
prefix = '/nvme1/data/animal-datasets-processed/kubric-multiview'
# sub_pattern = 's([5])-d([2])'
n_frames = 16
project_2d = false


[devices]
device = 'cuda:0'


[model]
track_3d = true
mode_3d = 'triplane' # 'minicubes'

# temporal processing
stride_length = 8
stride_overlap = 4

# resnet
downsample_factor = 2

# cube (only used for 3d)
cube_dim = 64
cube_extent = 5
# cube_extent = 500

# correlation
corr_levels = 4 
corr_radius = 3
corr_hidden_dim = 384
corr_output_dim = 256 

# triplane 
upsample_factor = 1

# transformer
max_freq = 10
n_iters = 4
embedding_dim = 384
latent_dim = 64 
n_virtual = 64 
n_heads = 8 
n_time_space_blocks = 3
embedding_factor = 4 


[training]
seed = 3
n_epochs = 600
scheduler_type = 'multisteplr'
# scheduler_type = 'onecyclelr'
use_half_precision = true
max_grad_norm = 1
checkpoint_freq = 25
eval_freq = 1
print_freq = 1
debug_ix = -1

[training.optimizer]
learning_rate = 1e-4
weight_decay = 1e-6
amsgrad = false

[training.scheduler]
milestones = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550]
gamma = 0.7
# milestones = [125]
# gamma = 0.1
# pct_start = 0.05
# cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 6
delta = 3
use_huber_loss = false
use_feature_loss = true

# weights for computing total loss 
vis_loss_weight = 2
conf_loss_weight = 1
coords_loss_weight = 0.05
feature_loss_weight = 1.0
