[wandb]
project_name = "posetail-finetuning"
path = "/groups/karashchuk/home/ruppk2/results/posetail-finetuning"
mode = "online"

[dataset]
batch_size = 1
num_workers = 96
prefix = "/groups/karashchuk/karashchuklab/animal-datasets-processed/posetail-finetuning"
datasets_to_exclude = ['tuthill-fly', 'allen-mouse']

[devices]
device = "cuda"

[model]
mode_3d = "minicubes"
hiera_requires_grad = true
stride_length = 8
stride_overlap = 4
downsample_factor = 2
cube_dim = 64
cube_extent = 5
corr_levels = 5
corr_radius = 2
corr_hidden_dim = 256
corr_output_dim = 128
upsample_factor = 1
max_freq = 10
n_iters = 4
embedding_dim = 384
latent_dim = 64
n_virtual = 64
n_heads = 8
n_time_space_blocks = 6
embedding_factor = 4
vc_head_requires_grad = true

[training]
seed = 3
n_iterations = 800000
scheduler_type = "onecyclelr"
max_grad_norm = 1.0
checkpoint_freq = 20480
eval_metric_freq = 16
val_freq = 64
print_freq = 1
debug_ix = -1

[dataset.train]
split_dir = "train"
n_frames = 16
min_res = 320
max_res = 384
cams_to_sample = [1, 8]
kpts_to_sample = [64, 128]
aug_prob = 0.25
enable_kpt_filtering = true
cam_thresh_for_vis = 1
balance_datasets = true
n_samples_per_dataset = -1

[dataset.val]
split_dir = "val"
n_frames = 16
max_res = 288
cams_to_sample = 5
kpts_to_sample = 32
aug_prob = 0.0

[dataset.test]
split_dir = "test"
max_res = 288
n_frames = 16
project_2d = false
aug_prob = 0.0

[training.optimizer]
learning_rate = 1e-5
weight_decay = 1e-5
amsgrad = false

[training.scheduler]
pct_start = 0.025
cycle_momentum = false

[training.losses]
gamma = 0.8
pixel_thresh = 3
delta = 6
use_huber_loss = false
vis_loss_weight = 1
conf_loss_weight = 1
coords_loss_weight = 0.1
occluded_coords_loss_weight = 0.01
feature_loss_weight = 1.0
